_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.9
            "6": 4.51.2
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 8
max_length:
    value: 128
model_name:
    value: gpt2
